In [2]:
print('hello')

hello


In [24]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [6]:
import numpy as np

In [7]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [9]:
mat[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [10]:
mat[3,4]

20

In [23]:
mat[:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [15]:
mat[:,1]

array([ 2,  7, 12, 17, 22])

In [16]:
mat[4,:]

array([21, 22, 23, 24, 25])

In [17]:
mat[3:,:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [18]:
np.sum(mat)

325

In [20]:
np.std(mat)

7.211102550927978

In [22]:
np.sum(mat,axis=0)

array([55, 60, 65, 70, 75])